# Site settings
name: Jeffrey Allen
email: jeffwayne256@gmail.com
url: url
description: "A blog and a matchup description"
author: "boomi"
title: "Big Test"
permalink: pretty
baseurl: /testjekyll

# social
github:
  username: jeffreyallen92

twitter:
  username: boomiFGC
