# Site settings
name: Boomi
email: jeffwayne256@gmail.com
url: url
description: "A blog and a matchup description"
author: "Boomi"
title: "Boomi's Street Fighter Journey"
permalink: pretty
baseurl: /sf

# social
github:
  username: hrefjeff

twitter:
  username: boomiFGC
