# Site settings
name: boomi
email: jeffwayne256@gmail.com
url: url
description: "A blog and a matchup description"
author: "boomi"
title: "Boomi's SFV Journey"
permalink: pretty
baseurl: /sfv

# social
github:
  username: jeffreyallen92

twitter:
  username: boomiFGC
